logging:
  level: debug
alexa:
  skill:
    name: dev-wegmans-shopping-list
    secret: 
aws:
  dynamodb:
    tableNames: 
      TOKENSBYCODE: devWegmansTokensByAccessCode
      TOKENSBYACCESS: devWegmansTokensByAccessToken
      TOKENSBYREFRESH: devWegmansTokensByRefreshToken
      PREREFRESHEDTOKENSBYREFRESH: devWegmansPreRefreshedTokensByRefreshToken
      ORDERHISTORYBYUSER: devWegmansOrderHistoryByUser
  lambda:
    functionNames:
      'cdk-wegmans-shopping-list': 'dev-cdk-wegmans-shopping-list'
      'cdk-wegmans-generate-access-code': 'dev-cdk-wegmans-generate-access-code'
      'cdk-wegmans-get-tokens': 'dev-cdk-wegmans-get-tokens'
      'cdk-wegmans-cron-order-history-updater': 'dev-cdk-wegmans-cron-order-history-updater'
      'cdk-wegmans-cron-access-token-refresher': 'dev-cdk-wegmans-cron-access-token-refresher'
      'cdk-wegmans-worker-prefix': 'dev-cdk-wegmans-worker-'
  sqs:
    queueNames:
      'worker-queue-prefix': 'dev-wegmans-worker-'
