logging:
  level: debug
alexa:
  skill:
    # Client ID and Secret set up in Alexa Skill Console -> Account Linking
    name: dev-wegmans-shopping-list-skill
    secret: AQICAHhEbkp592DXQD2+erIwWGqDeHoUQnAaX1Sw+4YW0087HwFTussnC+J0Qo3d5u/WgUpWAAAAgzCBgAYJKoZIhvcNAQcGoHMwcQIBADBsBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDI5Zp1Cj+TQua7gIMgIBEIA/YfRpHdztTPYlBLXQJ6c4z21mizACdWh78wBuTqLxxGo9GE52RRfkeJR1TIgfI7H5dIrpPKrl5YFA2S4fy6m4
aws:
  dynamodb:
    tableNames: 
      TOKENSBYCODE: devWegmansTokensByAccessCode
      TOKENSBYACCESS: devWegmansTokensByAccessToken
      TOKENSBYREFRESH: devWegmansTokensByRefreshToken
      PREREFRESHEDTOKENSBYREFRESH: devWegmansPreRefreshedTokensByRefreshToken
      ORDERHISTORYBYUSER: devWegmansOrderHistoryByUser
      PRODUCTREQUESTHISTORY: devWegmansProductRequestHistory
  lambda:
    functionNames:
      'cdk-wegmans-shopping-list': 'dev-cdk-wegmans-shopping-list'
      'cdk-wegmans-generate-access-code': 'dev-cdk-wegmans-generate-access-code'
      'cdk-wegmans-get-tokens': 'dev-cdk-wegmans-get-tokens'
      'cdk-wegmans-cron-order-history-updater': 'dev-cdk-wegmans-cron-order-history-updater'
      'cdk-wegmans-cron-access-token-refresher': 'dev-cdk-wegmans-cron-access-token-refresher'
      'cdk-wegmans-worker-prefix': 'dev-cdk-wegmans-worker-'
  sqs:
    queueNames:
      'worker-queue-prefix': 'dev-wegmans-worker-'
