logging:
  level: debug
  logDuration:
    logResolveValue: false
alexa:
  skill:
    # Client ID and Secret set up in Alexa Skill Console -> Account Linking
    id: amzn1.ask.skill.c3bd314f-e4c0-40f5-af97-468b9272240a
    name: dev-wegmans-shopping-list-skill
    utterance: devwedgies
aws:
  dynamodb:
    tableNamePrefix: dev
    tableNames:
      TOKENSBYCODE: devWegmansTokensByAccessCode
      TOKENSBYACCESS: devWegmansTokensByAccessToken
      TOKENSBYREFRESH: devWegmansTokensByRefreshToken
      PREREFRESHEDTOKENSBYREFRESH: devWegmansPreRefreshedTokensByRefreshToken
      PRODUCTREQUESTHISTORY: devWegmansProductRequestHistory
      ORDERHISTORYBYUSER: devWegmansOrderHistoryByUser

  lambda:
    functionNames:
      "cdk-wegmans-shopping-list": "dev-cdk-wegmans-shopping-list"
      "cdk-wegmans-generate-access-code": "dev-cdk-wegmans-generate-access-code"
      "cdk-wegmans-get-tokens": "dev-cdk-wegmans-get-tokens"
      "cdk-wegmans-cron-order-history-updater": "dev-cdk-wegmans-cron-order-history-updater"
      "cdk-wegmans-cron-access-token-refresher": "dev-cdk-wegmans-cron-access-token-refresher"
      "cdk-wegmans-worker-prefix": "dev-cdk-wegmans-worker-"
  sqs:
    queueNames:
      "worker-queue-prefix": "dev-wegmans-worker-"
